name: Build and Test

on:
  push:
    branches: [main]

jobs:
  trial:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out current code using public action
        uses: actions/checkout@v3
      - name: get the list of files in our current directory and its subdirectory
        run: | # this | enables us to multiple commands, good for formatting
          pwd
          ls -alR
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./
      - name: clean cache
        run: npm cache clean --force
      - name: install
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
      - name: test
        run: yarn test
